### ISSUE TITLE
Feature request: 'Can Send To Contacts Multiple Times' for automated sendouts

### ISSUE THREAD

**Issue by iamkeir** [putyourlightson/craft-campaign#100]
### Describe the solution you would like
Allow automated sendouts to have a `Can Send To Contacts Multiple Times` option like recurring sendouts.

### Describe alternatives you have considered
- Setting up multiple recurring sendouts, at every 30 minutes throughout the day.
- Custom module code.

### Additional context
I was able to achieve what I needed (job alert) using custom module code (thanks @bencroker), but it would also be quite elegant to be able to create such a thing via the admin UI + segment logic - so I think it would still be a useful addition. 

I do appreciate the concern regarding spam, but I think that should be the responsibility of the site owner/developer.

**Comment by bencroker** [comment]
Automated sendouts are intended for _marketing automation_ or _drip_ campaigns, whereby you can set up campaigns to be sent X number of minutes/hours/days after contacts subscribe to a mailing list.

What you are describing is a notification or alert email, which is not really within the scope of the Campaign plugin. I realise that your use-case may still benefit from mailing lists, subscriptions and other things that Campaign offers, but it doesn't sound like adding a `Can Send To Contacts Multiple Times` setting will really help you achieve what you want.

What we could consider is adding a setting to reduce the timespan within which the plugin will not send the same recurring sendout. Right now it is hard-coded so that a contact will receive a recurring sendout at most once per day, but if you could set this to 30 minutes then would that perhaps solve your problem?

**Comment by iamkeir** [comment]
Thanks for your response :) on reflection, I agree, and this feature request is misdirected.

I'm not quite sure if the increased frequency would actually help either, come to think of it - the mail only needs to go out if there are new job/s, so, even with segment/template logic, it would send empty emails if no new jobs existing. So perhaps the custom module code is the best way to go.

...perhaps this is just the tip of the iceberg of a much larger question/request...

Despite the difference between campaign/marketing and notification/transactional emails that you rightly point out, there is still so much overlap that it led us to try and find a system to unify them, specifically because:

- we use HTML emails for both
- we have some degree of Craft data in both
- both get sent to our mailing lists
- customers can control what they receive
- our client wants to be able to manage the content (to some degree) within the CMS

Despite it being beyond the scope, Campaign still does a very good job of this, to be fair! So it would seem counter-intuitive to have two separate systems managing all this.

...it almost feels like another type of sendout would be the ideal - an event-driven sendout with certain criteria. But that is a significant addition and perhaps, despite my points above, not part of the vision you have for Campaign.

Please feel free to close, depending on your thoughts to the above!

**Comment by bencroker** [comment]
We could consider adding a new _Alert_ sendout type that would be more along the lines of what you are trying to achieve. The [Webhooks plugin](https://github.com/craftcms/webhooks) provides an interface for listening for events, so we'd need to see if this could be used to trigger the alert or if there is a better approach. Can you please create a new issue with your use-case for discussion?
