### ISSUE TITLE
Q: Integration with Enupal Snapshot

### ISSUE THREAD

**Issue by j2is** [putyourlightson/craft-campaign#12]
Is it possible to integrate with Snapshot? So that you can send a pdf as an email attachment.
Any pointers would help, currently I'm just not sure how to go about it.
https://github.com/enupal/snapshot

**Comment by putyourlightson** [comment]
Email attachments are not currently supported by the plugin. This is intentional as having the ability to send hundreds or thousands of attachments in one go could wreak havoc on the system. My recommendation would be to add a public link to the PDF that Snapshot has created. That way your email stays light and you can track clicks to the PDF. I’m not familiar with Snapshot but assume that you can specify where to save the PDF to?

**Comment by j2is** [comment]
Thanks, I understand, yes I can include the link to the any attachments that would be more bulletproof.
