### ISSUE TITLE
Automated campaign – Resend to not opend addresses 

### ISSUE THREAD

**Issue by wedot** [putyourlightson/craft-campaign#127]
It would be great if you could add the feature that you can create an automated campaign for all those who have not opened an email in campaign XYZ, so that you can resend the newsletter to these addresses.

**Comment by bencroker** [comment]
Thanks for the suggestion, however the plugin specifically tries to avoid sending the same campaign to the same recipient multiple times. Since the open reports can never be 100% accurate (as some email clients will block the tracking script), this doesn't seem like a feature we would want to build into the plugin.
