### ISSUE TITLE
Sendout getting stuck with Mailgun

### ISSUE THREAD

**Issue by samstevens** [putyourlightson/craft-campaign#138]
### Describe the bug
If an invalid email address ends up on a mailing list list, mailgun will reject the email and the sendout will become stuck. 

Fixing the invalid email address will allow the sendout to continue. 

Logs when sendout gets stuck: 

`Sending of the sendout "ABC Campaign" failed after 3 send attempt(s). Please check that your Campaign email settings are correctly configured and check the error in the Craft log.`

### To reproduce
Steps to reproduce the behaviour:

- Create a new campaign/sendout
- Include a contact with an invalid email address (try a .con or othe varients of invalid email addresses)
- Send
- Check logs

### Expected behaviour
The sendout should ignore the invalid email address error and continue to send the remaining emails.

This might be a more reliable email validation library
https://github.com/egulias/EmailValidator

### Versions
- Plugin version: 1.15.2
- Craft version: Craft Pro 3.4.17.1
- Mailgun Plugin: 1.4.3

### Thanks
👍

**Comment by bencroker** [comment]
As explained in chat, this is not a bug but expected behaviour. The reasoning is that if Mailgun refuses to send an email `maxSendAttempts` number of times (set to 3 by default), then something is likely wrong. Rather than continue trying to send the rest of the emails, which could result in Mailgun eventually blacklisting your account, the sendout is stopped with the appropriate warning. You can of course increase [maxSendAttempts](https://github.com/putyourlightson/craft-campaign/blob/1.15.3/src/config.php#L63-L64) to whatever number you want.

Ideally, you would not have any invalid email addresses in a mailing list, but these appear to be email addresses that are formatted correctly but whose MX resource record is not found (as in your `.con` example). If the Campaign plugin was to have to verify the MX resource record of every single email address then it would become slowed down to the point of being unusable. So I think the responsibility should remain on the user to ensure that the email lists contain valid addresses, manually removing any that are refused by Mailgun.

**Comment by bencroker** [comment]
I've improved log messages of failed sendouts in https://github.com/putyourlightson/craft-campaign/commit/846c0247791c55020b55d6e86202d8dbba74cfb3, adding the email address that failed.

I'm also looking into whether there is a more elegant way to continue the failed sendout without causing too much damage ;)

**Comment by bencroker** [comment]
Added the `maxSendFailsAllowed` config setting in https://github.com/putyourlightson/craft-campaign/commit/6bb97ac74224408a3c95c7938c31339759246e9c.
