### ISSUE TITLE
When saving a new contact, come back to contact page or select that contact in the list

### ISSUE THREAD

**Issue by bossanova808** [putyourlightson/craft-campaign#147]
### Is your feature request related to a problem? Please describe.

When manually creating a new contact, you can't add that contact to a mailing list until they are saved.

So first we need to search contacts to see if they exist?

If no - add a new contact.  Save.

We're dropped back to the list (in our case over 8000 names) - but we have to then search again to find them, and only then can we add them to a mailing list.

I realise this is kind of Craft standard behaviour (frequently irritating standard behaviour, TBH) - and that one can hit Ctrl-S to stay on the new contact page.  But that's very easy to forget and it makes the adding contact workflow significantly more tedious than it needs to be.

### Describe the solution you would like

Save either stays on the contact page or when dropped back to the list it is filtered to show or at least have selected the new contact.

(Also, sorry for hammering you with issues - loving Campaign and seeing more uses for it, hence new things popping up!)

**Comment by bencroker** [comment]
In addition to to `Ctrl-S`/`⌘S` keyboard shortcut, you have a `Save and continue editing` button in the button group dropdown. 

![Screenshot 2020-05-21 at 09 38 17](https://user-images.githubusercontent.com/57572400/82535761-a1ef0180-9b47-11ea-88b6-f11f1a0ea7af.png)

I understand your point about the long process of filtering contacts, however as you correctly note, changing the behaviour of the save button would go against the standard behaviour of Craft. Instead of doing this, I will be waiting to see what CP UX changes come in Craft 4 (alpha expected to be released in Q4 2020) and Campaign 2.0.0 will follow whatever standard behaviour the Craft 4 CP does. 

Thanks for the feedback and suggestions and I'm glad to hear you're enjoying Campaign!
