### ISSUE TITLE
[Question] Some button text not able to be applied translation

### ISSUE THREAD

**Issue by watarutmnh** [putyourlightson/craft-campaign#249]
### Question
Is there any way to translate the button text on the top right the corner of the campaign list page?
I can't make it translate with a translation file.

I have also the same request for other buttons such as 'New  mailing list', 'New segment', 'New sendout', etc. 

![screenshot 2021-08-17 at 11 43 24](https://user-images.githubusercontent.com/6081378/129655884-d069e181-f96a-42f4-808d-bbf5f51bf138.png)

Thanks,

**Comment by bencroker** [comment]
The "New X" translations should work if correctly set up. 
https://github.com/putyourlightson/craft-campaign/blob/60da72d875d305e1f440dd234b7f19c08da581d4/src/translations/en/campaign.php#L339-L349

**Comment by scandella** [comment]
Same question as @watarutmnh.

I've completed many translation values and some part of the plugin still does not received the translation string.
The "New campaign" for instance never get translated and some other buttons remain in English too.
For instance the "Mailing lists" entry in the sidebar stay untranslated even if I have a french value for it in my "fr" translation folder. All the other entries in the sidebar works.

By the way, the localization of the plugin is required for a non english speaker user. In French, for instance, the english wording is confusing, because we have some very different concept to define what a "campaign" is ("Campaign" would be used instead of "Sendout"). So a French non english speaker user would have no clue where to begin to use the plugin and would always be very confused by the vocabulary, even with some explanations. That is why it is critical that I present the plugin to my users with the most complete localization.
If I provide you the French translation file, would you be interesting in including it to your distribution?

Thanks for your help.

![CleanShot 2021-08-18 at 18 48 47](https://user-images.githubusercontent.com/1114307/129939828-6af053c6-d03f-43e8-81a4-2dd658ccff8c.png)
![CleanShot 2021-08-18 at 18 53 59](https://user-images.githubusercontent.com/1114307/129939972-b9af93bb-6e02-4a8e-8924-fa45fbd778b8.png)

**Comment by bencroker** [comment]
Yes, please feel free to submit a PR with a translation file!

Can you try "Mailing Lists"? I think the capitalisation is important here. I'll look into why "New mailing list" is not working.

**Comment by scandella** [comment]
> Can you try "Mailing Lists"?  I think the capitalisation is important here

It works. As I have duplicated the .en file, I thought all the english entries were correct…

Another request: it would be nice if we could change the name of the plugin too. Because "Campaign" does not make much sens in French for your plugin.

**Comment by watarutmnh** [comment]
> The "New X" translations should work if correctly set up.
> https://github.com/putyourlightson/craft-campaign/blob/60da72d875d305e1f440dd234b7f19c08da581d4/src/translations/en/campaign.php#L339-L349

'New contact' is working applied its translation but 'New campaign', 'New mailing list', 'New segment', 'New sendout' are not.

**Comment by watarutmnh** [comment]
I would like to submit PR of Japanese translation too!

**Comment by bencroker** [comment]
> Another request: it would be nice if we could change the name of the plugin too. Because "Campaign" does not make much sens in French for your plugin.

@scandella Is it that the meaning of the word "Campaign" makes little sense? Because you could just think of it as a name, like "Craft" or "Yii" or anything else really...

> 'New contact' is working applied its translation but 'New campaign', 'New mailing list', 'New segment', 'New sendout' are not.

@watarutmnh I'm looking into why this is.

**Comment by bencroker** [comment]
Fixed in https://github.com/putyourlightson/craft-campaign/commit/a7a32913f83a6829f68e133a5a4de26ac282e068 for the next release.

**Comment by scandella** [comment]
> @scandella Is it that the meaning of the word "Campaign" makes little sense? Because you could just think of it as a name, like "Craft" or "Yii" or anything else really...

@bencroker, I agree with you from a developper stand view. But ultimately, a Craft site is managed by non technical users (writers and copy editor in my case) and they don't have a clue that Craft or Yii or whatever tech name are even behind the curtains. Why should they? Unlike many CMS (for instance, think of the mess WordPress is for a beginner end user: nothing make sens, developper tools and redactor widgets are all over the place…), Craft allow developpers to present a clean and usable environment with minimum learning curve to their non technical users, because many details of the environment can be customized.
And you know better than me that you're never too obvious in design and wording choice: despite of maintaining a very good documentation for your plugins, you are stil receiving some awkward questions from people like me!
So if an end user wants to create and send a newsletter, I would rather present him a "Newsletters" button in the CP sidebar instead of a"Campaign" button for which I would have to explain him many times that it stand for "Newsletters".
For instance, I like the Freeform plugin's customize button name option because it allow me to present a button "Formulaires" (French for "forms") to my end users so when they want to manage some forms, I don't have to explain anything to them. You'll see in the screen below that the "Campaign" button is not so friendly for them…
Sorry for being too long…
 
<img width="454" alt="CleanShot 2021-08-21 at 18 41 39@2x" src="https://user-images.githubusercontent.com/1114307/130328995-643454ec-87d2-4112-bffd-12a09b3671b7.png">

**Comment by bencroker** [comment]
@scandella Thanks for your explanation, it makes a lot of sense. I've made the plugin name translatable in https://github.com/putyourlightson/craft-campaign/commit/711cddb25b94c82852027f219e51f82a57910449. It will use the translation for "Campaign", so in your case it will appear as "Newsletter", which is hopefully more intuitive for clients. I wanted to avoid using a plugin setting for this, as Freeform does, and I think that for this plugin it works sufficiently well.

**Comment by bencroker** [comment]
Released in version 1.21.0.

**Comment by bencroker** [comment]
@watarutmnh any interest in submitting a PR with your Japanese translation? @scandella submitted a French one which has been merged for the next release!

If you are interested then please reference the latest version of https://github.com/putyourlightson/craft-campaign/blob/develop/src/translations/en/campaign.php, which contains all of the translated text used by the plugin.

**Comment by watarutmnh** [comment]
@bencroker Excuse me for no reply since last time. I have been so busy these days but hopefully start translating next year!
But thank you remind me this :)

**Comment by bencroker** [comment]
Ok, sounds good @watarutmnh!
