### ISSUE TITLE
Send test emails to multiple contacts (or a list!)

### ISSUE THREAD

**Issue by bossanova808** [putyourlightson/craft-campaign#256]
### Is your feature request related to a problem? Please describe.

I would love to be able to select multiple contacts, and/or a list (like 'staff'), here:

![image](https://user-images.githubusercontent.com/731309/131619116-41873e98-3002-4f56-9196-5c822f32830f.png)

Would just make the process of developing content in Campaign easier.

Thanks for thinking about it!

**Comment by bencroker** [comment]
This is a great idea, thanks!

**Comment by alexanderbuergin** [comment]
I would love to see this.

**Comment by bencroker** [comment]
Added the ability to send test emails to multiple contacts at once and to set multiple default test contacts in the campaign type settings in https://github.com/putyourlightson/craft-campaign/commit/22f349a2efaac3568f59e420af1d952641c48381 for the next release.

Since you can now set multiple default test contacts in the campaign type settings, I see no reason to add the ability to send tests to entire mailing lists.

**Comment by bencroker** [comment]
Released in version 1.21.0.
