### ISSUE TITLE
[Question] Subscribe and Unsubscribe verification email templates not working

### ISSUE THREAD

**Issue by JJefferyDev** [putyourlightson/craft-campaign#270]
### Question
I have created unique subscribe and unsubscribe twig templates that only seem to be working with basic html.  Whenever I try to include a twig variable, such as the subscribeUrl or unsubscribeUrl, the template doesn't work and the emails revert to the default.  I have included code examples of what does and does not work below.  What am I missing?

### Additional context
Plain html that works:
`````
Hello,
    <br><br>
Thank you for signing up for the company mailing list.  To complete your subscription, please follow the link below:
<br><br>
<a href="https://google.ca">google.ca</a>
`````

Twig code that does not work, being replaced by the default:
````
{% extends 'campaign/_layout' %}

Hello,
    <br><br>
Thank you for signing up for the company mailing list.  To complete your subscription, please follow the link below:
<br><br>
<a href="https://google.ca">google.ca</a>

<a href="{{ subscribeUrl }}">Subscribe to this mailing list</a>
```

**Comment by bencroker** [comment]
Ensure that that `campaign/_layout` template exists in your site, otherwise you should remove the `extends` tag.

The "Subscribe Verification Email Template" can use any of the available template tags: `message, url, mailingList, pendingContact`. Note that `subscribeUrl` is not a valid template tag.

<img width="695" alt="Screenshot 2021-09-03 at 12 23 36" src="https://user-images.githubusercontent.com/57572400/131991233-e5962be5-c59a-44ea-817c-a41b9721c570.png">
