### ISSUE TITLE
Campaign URI format returning incorrect browserVersionUrl

### ISSUE THREAD

**Issue by iparr** [putyourlightson/craft-campaign#291]
I have a weekly newsletter setup using the 'Recurring' campaign type.

I have a `{{ browserVersionUrl}}` link in my template.

I use the following 'Campaign URI Format': `newsletter/{sendDate|date('Y/m/d')}`

However, today this is generating a link for _last weeks_ newsletter (i.e. `newsletter/2022/02/10`, not `newsletter/2022/02/17`).

What Campaign URI format should I use to ensure that the date of the actual sendout - i.e. when it's sent, not when the first recurring campaign was scheduled - is generated?

(I know I can use todays date, but this is a bodge because what if I'm previewing future/past newsletters, etc.)

**Comment by bencroker** [comment]
The `sendDate` here represents the scheduled send date of the campaign. Since recurring campaigns can only have a single URI, you can't really have a unique URI per individual sendout.

**Comment by iparr** [comment]
Thanks Ben. I don't want to do something too 'imaginative' - how do people usually deal with this scenario? - I'm sure a browser-friendly archive of sendouts as they are generated is quite a common use-case.

**Comment by bencroker** [comment]
Most organisations that I am aware of use regular/scheduled sendouts for their newsletters, since they have custom content and like to maintain an archive of them. Recurring sendouts are generally used for more generic updates so rarely need unique URLs.

I suppose you could use a query string to get the specific content for any given week. For example with a URL `newsletter?from=2022-02-10&to=2022-02-16`:

```twig
{% set from = craft.app.request.get('from') %}
{% set to = craft.app.request.get('to') %}
{% set entries = craft.entries.after(from).before(to).all() %}
```
