### ISSUE TITLE
Dates

### ISSUE THREAD

**Issue by stovepot** [putyourlightson/craft-campaign#3]
Is it possible to get the postDate of an entry or is the sendout.sendDate the only option?

**Comment by putyourlightson** [comment]
It depends where, but if you mean in your campaign template, then it should be possible just as you would expect with `{{ entry.postDate }}`.

**Comment by stovepot** [comment]
Using:
`{% set campaigns = craft.campaign.campaigns.campaignType('typeA').all() %}`
` {% for campaign in campaigns %}`
            ` {% set image = campaign.bannerImage.one() %}`
`{{ entry.postDate }}` : Variable "entry" does not exist 
or
`{{ campaign.postDate }}`: Calling unknown method: putyourlightson\campaign\elements\CampaignElement::postDate()
`{% endfor %}`

**Comment by putyourlightson** [comment]
I'm not sure what you're trying to get the post date of. If an entry, then you'll have to fetch it in your template first. 

Campaigns don't have post dates, as they are not "posted" per se. Since they are elements though, you will be able to access the `dateCreated` and `dateUpdated` properties. Does that help?

**Comment by stovepot** [comment]
Thanks Ben, I’ll stick to the sendout date. Confirming the entry.postdate does not work.

**Comment by putyourlightson** [comment]
Ok, just beware of how exactly you reference the sendout in your template, as it only exists in sent emails, so you should always check for it first.

```
{% if sendout %}
   Sent on: {{ sendout.sendDate }}
{% endif %}
```
