### ISSUE TITLE
Email validation on import

### ISSUE THREAD

**Issue by robinbeatty** [putyourlightson/craft-campaign#300]
### Question
Hey, not sure if this is a support request or a feature request, but I'm dealing with an issue from a client's csv import, to find there is an invalid email address in their csv and causes the whole import to fail. Is there a soft fail feature to just skip and log invalid entries? Thanks

### Additional context
PHP version | 7.4.25
OS version | Linux 4.4.299-icpu-082
Database driver & version | MySQL 5.7.36
Craft edition & version | Craft Pro 3.7.18
Yii version | 2.0.43
Twig version | v2.14.8
Guzzle version | 6.5.5
Campaign | 1.21.1

**Comment by bencroker** [comment]
Imports shouldn't fall over completely if there's an issue, instead they should carry on and report any failed imports. Are you seeing otherwise?

<img width="882" alt="Screenshot 2022-02-28 at 17 24 42" src="https://user-images.githubusercontent.com/57572400/156029385-0f733ac9-1296-4a36-b317-bcddf4193ee2.png">

**Comment by robinbeatty** [comment]
Ok thanks – in this case I'm assuming a connection between two unrelated problems, after finding some invalid (typos) email addresses in roughly the same place as the import fails. I think the import failing is most likely a php memory issue in our environment.

**Comment by robinbeatty** [comment]
(updated my question to be more specific to this particular case)

**Comment by bencroker** [comment]
Ok, so is this particular issue resolved?
