### ISSUE TITLE
Bounced email addresses blocked sendout

### ISSUE THREAD

**Issue by Rommert** [putyourlightson/craft-campaign#304]
Recently, a campaign was not sent because 2 bounced email addresses were blocking the sendout. The campaign contained 200 email addresses. And blocked for example at 13/200... We were able to find out the bounced email addresses came via Postmark.

We had to manually set the contact to a "bounced" status in Campaign. Is there a possibility that bounced contacts (via Postmark) are automatically set to bounced status in Campaign via the API?

**Comment by bencroker** [comment]
Yes, you can set up bounce handling using webhooks, as described at https://putyourlightson.com/plugins/campaign#bounce-and-complaint-handling

**Comment by Rommert** [comment]
@bencroker, the webhooks were enabled. We have enabled the following settings:


<img width="484" alt="Schermafbeelding 2022-03-28 om 10 34 41" src="https://user-images.githubusercontent.com/2290530/160359150-5282dfa3-5593-4a2a-8624-0a6fff4b6891.png">

Did we miss something?

**Comment by bencroker** [comment]
There have been issues reported of Postmark adding its own unsubscribe link to emails. For that reason you should probably check the "Subscription Change" checkbox, see https://github.com/putyourlightson/craft-campaign/issues/286

Otherwise your settings look fine. You can manually mark the contacts as bounced in Campaign, ensure you're on the latest version of the plugin and let me know if this ever again.
