### ISSUE TITLE
Subscribe form issue for mailing list across multi sites

### ISSUE THREAD

**Issue by watarutmnh** [putyourlightson/craft-campaign#306]
### Question
I had your help on the ticket below and I got the form successfully working file. https://github.com/putyourlightson/craft-campaign/issues/252

But today I noticed that the form gets an 404 error says:'Mailing list not found.'  when it submitted.

[HTTP 404 – Not Found](http://en.wikipedia.org/wiki/List_of_HTTP_status_codes#404) – [yii\web\NotFoundHttpException](http://www.yiiframework.com/doc-2.0/yii-web-notfoundhttpexception.html)

This form at the site A let users to subscribe the mailing list associated with site B and redirect to success page with:
```
<input type="hidden" name="redirect" value="{{ 'subscribe-success'|hash }}" />
```

The template "subscribe-success.twig" is located at site B but I remember It was working with no issue...

I need the help to resolve this error.
Thanks,

**Comment by bencroker** [comment]
The redirect value may need to be more specific than just `subscribe-success`, can you give some more specifics as to which URL you're being redirected to?

**Comment by watarutmnh** [comment]
Something like this:
 
site A
https://store.example.com

site B (URL to redirected)
https://example.com/subscribe-success

**Comment by bencroker** [comment]
So does your redirect input look like this?

```twig
<input type="hidden" name="redirect" value="{{ 'https://example.com/subscribe-success'|hash }}" />
```

Also, does the subscription to the mailing list actually go through successfully?

**Comment by watarutmnh** [comment]
Neither
`<input type="hidden" name="redirect" value="{{ 'subscribe-success'|hash }}" />`
nor
`<input type="hidden" name="redirect" value="{{ 'https://example.com/subscribe-success'|hash }}" />`
works.

The site B have subscribe form too and it works so the mailing list has no problem.

**Comment by bencroker** [comment]
And what is the resulting redirect URL...?

**Comment by watarutmnh** [comment]
it gets 404 and NotFoundHttpException error due to $mailingList === null

**Comment by watarutmnh** [comment]
it is from putyourlightson/craft-campaign/src/controllers/FormsController.php Line 67

**Comment by bencroker** [comment]
If that is the exception being thrown, then subscribing must be blocked. It looks like it is not possible to subscribe to a mailing list in a different site though, since each mailing list type can only belong to a single site. I'd suggest you work around this by creating one mailing list type per site.

**Comment by watarutmnh** [comment]
Okay I understand, It is a pity that there is no way to subscribe a mailing list in the same system.
But Thanks.

**Comment by bencroker** [comment]
It was intentional to make mailing lists site-specific, but it is also easy to create sendouts that can send to multiple mailing lists.

**Comment by apitel** [comment]
I came across this same issue for a site setup for multiple languages. It would be nice not to have to create separate mailing lists for all languages, but the comments here suggest that's what is required. 

I came across this issue because the documentation suggests that with `{{ hiddenInput('siteId', 2) }}` we can identify the appropriate site that the mailing list exists, but that did not achieve the desired affect.

**Comment by bencroker** [comment]
@apitel as explained above, this is intentional. This way, you can have unique subscribe and verification templates per site.

As per the docs at https://putyourlightson.com/plugins/campaign#subscribe-form, you should be able to create a subscribe form to a mailing list in another site as follows. Note that this capability was only added in version [2.5.3](https://github.com/putyourlightson/craft-campaign/blob/develop/CHANGELOG.md#253---2023-02-03). If it is not working for you then please create a new issue and I’ll take a closer look.

```twig
<form id="subscribe-form" method="post">
    {{ csrfInput() }}
    {{ actionInput('campaign/forms/subscribe') }}
    {{ hiddenInput('mailingList', mailingListSlug) }}

    {# Specify a site ID – required only if the mailing list does not exist in the current site. #}
    {{ hiddenInput('siteId', 2) }}
</form>
```

**Comment by apitel** [comment]
Thanks @bencroker for the note about the compatibility version. I updated the Campaign plugin and everything works as expected now.

**Comment by bencroker** [comment]
Glad to hear it!
