### ISSUE TITLE
Add `isSendoutPreview` variable

### ISSUE THREAD

**Issue by pl-mnm** [putyourlightson/craft-campaign#362]
We are currently adding `{% header 'Content-Type: text/plain' %}` to our plain text templates, and that causes the entire sendout entry in CP to show as plain text. With a `isSendoutPreview` we could conditionally add that header.

**Comment by bencroker** [comment]
What's the reasoning for adding that header? Plaintext templates are really only used for rendering the plaintext version of sendouts, in which case headers should not be required.

**Comment by rungta** [comment]
Hey @bencroker, our primary use-cases are:
1. Previewing these templates in the browser to test them out.
2. Perhaps providing a “View this email in the browser” link for the plain text version as well.

Currently we’re using a `?text` GET parameter in our URLs to render the plain text templates instead of the regular HTML templates. Adding the header lets us view the email with whitespace formatting etc intact in the browser.

**Comment by bencroker** [comment]
@rungta in that case, I imagine using something like `?text=1` should work well with the following.

```twig
{% if craft.app.request.get('text') %}
    {% header 'Content-Type: text/plain' %}
{% endif %}
```
