### ISSUE TITLE
Add more logging during sending

### ISSUE THREAD

**Issue by bencroker** [putyourlightson/craft-campaign#385]
Adding more logging during the sendout process should help make things more transparent, as well as easier to troubleshoot if “unexpected things” happen. Ideally added to both Campaign v1 and v2, to accomodate our “legacy” users.

**Comment by MattWilcox** [comment]
Just to give a general scenario we recently hit:

- A client reports that an old Campaign has suddenly and unexpectedly begun to be sent out.
- They forward us mail as proof - yep, it's sending out.
- We check that particular campaign and see it had been scheduled for send out 5 months earlier, and presumably went out fine then. We spot that it has indeed been sent out again that day.
- We believe the client disabled the campaign in panic *after* this send-out happened.
- We try to tally up things in the back-end and spot that the Reports area says no campaigns have ever been sent... but the campaign detail page says it was sent that day.

So, it's "any" sort of logging that might help untangle that sort of mess:

- Was there client error and the last sendout was triggered manually by accident somehow?
- Was there a schedule glitch of some sort that caused the sendout?
- Why do the Report and Campaign seemingly not agree?

**Comment by bencroker** [comment]
Thanks, @MattWilcox! For the record (from our Discord conversation), your client’s site is running on Campaign 1.24.1.

> We check that particular campaign and see it had been scheduled for send out 5 months earlier, and presumably went out fine then. We spot that it has indeed been sent out again that day.

Assuming this Sendout has a type of “Scheduled”, are you sure that the sendout finished sending completely 5 months earlier? Is there a cron job set up to [run pending sendouts](https://putyourlightson.com/plugins/campaign#running-pending-sendouts) on a recurring schedule that would prevent stale scheduled sendouts from being sent in the long-term future?

> We try to tally up things in the back-end and spot that the Reports area says no campaigns have ever been sent... but the campaign detail page says it was sent that day.

Disabled campaigns will not show up in the campaign reports page. Enabling the campaign will allow you to view the report again. You can first check that the sendout is not in a state of “Pending“ to ensure it is not sent again.

**Comment by MattWilcox** [comment]
`Disabled campaigns will not show up in the campaign reports page` Good to know, thanks - what we were seeing in that regard makes sense then, though just as a bit of feedback - historical reporting may be something that clients would actually want to see regardless of the associated campaign being disabled, for historical purposes and comparisons.

With regard to the original issue - we can't be sure that the original actually completed, just because of the timeframe - but it seems extremely unlikely that 5 months should elapse before the job got tried again if it hadn't completed.

Can confirm that there's a CRON running too. I remain a little suspicious that the original problem could have been a client mistake or unintended action - but back to the topic, that's why some sort of action-logging as a matter of course would help debug if that's what happened or if there's "an actual bug".

Cheers Ben!

**Comment by bencroker** [comment]
Added some additional logging in https://github.com/putyourlightson/craft-campaign/commit/58597d67c216a63cafa9f9427a47c6e7733e8279 and released in version 2.8.0.

**Comment by MattWilcox** [comment]
2.8 only, or also the 1.x branch?

**Comment by bencroker** [comment]
Just 2.8.0.

**Comment by bencroker** [comment]
Just 2.8.0, but will add to v1 as well shortly.

**Comment by bencroker** [comment]
Released in version 1.24.2.

**Comment by MattWilcox** [comment]
Just a quick thanks, Ben. Much appreciated.
