### ISSUE TITLE
Formie Integration: Option to Skip "Subscribe Verification"

### ISSUE THREAD

**Issue by adrianjean** [putyourlightson/craft-campaign#404]
We use Formie for email newsletter sign-ups because we also create a new Contact Entry for each newsletter sign-up submission.

Campaign (rightly) respects the Mailing List Type's "Subscribe Verification" setting. If turned on, subscribers using our Formie form, must verify their email before they are subscribed to the mailing list.

However we have an internal "contact ingestion form" for inputting contacts using Formie, but these contacts don't need Subscription Verification to join the mailing list. 

**Is it possible to add an "Ignore Subscribe Verification" switch on the Formie integration config for Campaign to allow the contact to be added to the list, while leaving the "Subscribe Verification" setting the way it is for general public?**

(Not sure if this is a Campaign plugin request, or a Formie plugin request)

**Comment by bencroker** [comment]
> Is it possible to add an "Ignore Subscribe Verification" switch on the Formie integration config for Campaign to allow the contact to be added to the list, while leaving the "Subscribe Verification" setting the way it is for general public?

I don’t see us adding such a specific setting to Campaign. The simplest workaround is to have one mailing list type for the general public that requires verification and another for your internal “contact ingestion form” that doesn’t. Assuming there is a form for each of these use-cases, the implementation should be relatively straightforward, otherwise you can use conditionals (in Twig or JS) to determine the form to send to.
