### ISSUE TITLE
Export campaigns and import to new site

### ISSUE THREAD

**Issue by joostclevis** [putyourlightson/craft-campaign#412]
Is it possible to export all campaigns from a website into a different website? 
We have to merge two websites together and one has a about 200 sent campaigns. 
Would be nice if it was possible to export and import them.

**Comment by bencroker** [comment]
It depends on what you're trying to accomplish. It's possible to export basic campaign report data from the campaign index page, but that is intended for importing into other systems such as a spreadsheet. 

You could use the Feed Me plugin to export the campaigns and then use it to import them into the second CMS, if the goal is to display the campaigns on the second site. If your goal is to import the campaigns along with all related data and stats then there's no way to do this currently.

**Comment by joostclevis** [comment]
@bencroker The main goal is to keep the archive available on the new site.
I already tried Feed Me, but if i'm not mistaken that's only for importing. 

Also, if i check Feed Me, i don't see a way to import data into Campaign. Am i missing something?

**Comment by bencroker** [comment]
In that case you can export the campaigns on the index page, followed by importing them using Feed Me.

It turns out there was a bug preventing Feed Me from registering the Campaign plugin’s element types. I’ve fixed this in https://github.com/putyourlightson/craft-campaign/commit/2db788502a83e3c61fe0676cc206d1c94a349761 for the next release. You can the fix early by running `composer require putyourlightson/craft-campaign:v2.x-dev as 2.8.6`.

<img width="1072" alt="Screenshot 2023-09-14 at 11 28 12" src="https://github.com/putyourlightson/craft-campaign/assets/57572400/9e90bda9-2ec4-4727-9965-622df4de7fd5">

**Comment by bencroker** [comment]
Released in version 2.8.6.
