### ISSUE TITLE
Send order has changed - no longer oldest contacts first

### ISSUE THREAD

**Issue by bossanova808** [putyourlightson/craft-campaign#423]
(Hope you're having a great time at .all - no urgency on this!!)

I have noticed with Craft 4 / Campaign 2 (up to date with both) - that our Campaigns no longer send in the same order as they used to - they used to send to the oldest contacts first (i.e. starting with me, user 1) - but I am not quite sure what the order is now, seems basically random.

I definitely preferred the older behaviour (and it meant our oldest customers were rewarded by getting notice of specials slightly before others etc) - and am wondering why this change was made, and if there is some chance it could be reverted (even if optionally) - to restore the old behaviour.

Thanks Ben!

**Comment by bencroker** [comment]
Thanks for your understanding. I agree that the order should be more deterministic and will look into what changed and see if I can resolve for the next release.

**Comment by bencroker** [comment]
I’ve made it so that pending contacts are fetched in order of their ID, which should correspond to oldest first, in https://github.com/putyourlightson/craft-campaign/commit/42668c23ed60f475c24bce57b54cdb52c3b1b4e9. You can test this by running `composer require "putyourlightson/craft-campaign:dev-develop as 2.8.8"`.

**Comment by bencroker** [comment]
Released in version [2.9.0](https://github.com/putyourlightson/craft-campaign/releases/tag/2.9.0).
