### ISSUE TITLE
Add ability to integrate with Sparkloop

### ISSUE THREAD

**Issue by jacksoncool** [putyourlightson/craft-campaign#427]
A GREAT feature to add to Campaigns is the ability to integrate with Sparkloop.  Sparkloop has A number of vendors that let their Users connect to them via leveraging their email provider's API. Then you can use Sparkloop to either get paid to recommend other publications or pay other newsletters to recommend yours.  

https://sparkloop.app/
https://sparkloop.app/partner-network
https://docs.sparkloop.app/#using-the-api-key
https://help.sparkloop.app/en/articles/7879730-list-of-esps-sparkloop-features-work-with

**Comment by bencroker** [comment]
Is there anything stopping you from doing this in a custom module/plugin?

**Comment by jacksoncool** [comment]
To be honest, I thought it would be just a great new feature of Campaign. A way for people who are managing their own newsletters through Craft Campaign to leverage additional monetization avenues. I would think probably better as a first party add-on vs me building out something.

**Comment by bencroker** [comment]
Thanks for the suggestion. I’m unfamiliar with Sparkloop, and I imagine that there are lots of other integrations that would be possible, which is why Campaign is made to be extensible using events. This particular integration is not something we intend to add in the foreseeable future, but if you end up creating your own integration then I’d be happy to take a look at your approach and the result.

**Comment by jacksoncool** [comment]
Sounds good. Just FYI Sparkloop is super popular, and the big external email platforms have integrated with it.

**Comment by bencroker** [comment]
I’m sure they have... in addition to integrating with Google Analytics, Salesforce, etc. The list goes on and on. The priority with the Campaign plugin is to make sure it does what it promises, and does it well. Integrations with third-party services are possible via custom modules/plugins.
