### ISSUE TITLE
Support for List-Unsubscribe-Post header

### ISSUE THREAD

**Issue by efedorenko** [putyourlightson/craft-campaign#467]
### Feature Request

Hi Ben,

You're probably familiar with [Google & Yahoo's new requirements](https://postmarkapp.com/blog/2024-gmail-yahoo-email-requirements) for email senders in 2024, and support for one-click unsubscribe using the [`List-Unsubscribe` email header](https://postmarkapp.com/blog/list-unsubscribe-header) is one of them. This requirement will be enforced starting in June.

Most ESPs take care of that automatically when you use their built-in unsubscribes, but can't do it if the Campaign manages unsubscribes. I use Postmark and need to comply with this requirement ASAP. What's the best way to do it without transferring unsubscribes to Postmark?

Thank you!

### Plugin Version

2.14

**Comment by bencroker** [comment]
Hi Eugene, this is on my list of things to add to the plugin, but thanks for the reminder! I'll prioritise this feature and get a release out in the coming days. Is there anything else you've spotted that needs adding in order to comply with the new rules? From what I've seen, it is all on the sending domain, delivery service and the body content, so nothing that the plugin can enforce.

**Comment by efedorenko** [comment]
Thanks for prioritizing this, Ben! I think unsubscribes is the only part handled by the plugin.

**Comment by bencroker** [comment]
Release coming tomorrow, along with an article.

**Comment by bencroker** [comment]
Released in [3.1.0](https://github.com/putyourlightson/craft-campaign/releases/tag/3.1.0) and [2.15.0](https://github.com/putyourlightson/craft-campaign/releases/tag/2.15.0), and published an accompanying article at https://putyourlightson.com/articles/complying-with-gmail-yahoos-email-sending-requirements.
