### ISSUE TITLE
Sendout progress is completed, but status stays on pending

### ISSUE THREAD

**Issue by lennonpuype** [putyourlightson/craft-campaign#505]
### Bug Report

Hi, for some reason the sendout of our last campaign is still on pending, even after reaching progress 100%.
I looked into the logs and it actually says it is completed. Clearing the cache didn't help. I am not really to sure where to look at to fix this.

**Logs**
![Screenshot 2024-11-26 at 16 45 58](https://github.com/user-attachments/assets/4e333c82-5246-4513-88a6-925b633163ee)

**Sendout**
![Screenshot 2024-11-26 at 16 46 34](https://github.com/user-attachments/assets/3fcd6c15-d30a-4fad-bf37-6b9aff5174ce)

### Plugin Version

3.5.6

### Craft CMS Version

5.5.0.1

### PHP Version

8.2.26

**Comment by bencroker** [comment]
Can you try continuing the sending and see if that gets it to complete?

**Comment by lennonpuype** [comment]
Hmm weird before it was at 100% like I said and it also triggered as completed in the logs. Now I looked and it said 99% with 7 expected recipients. I used `./craft campaign/sendouts/run` to run the incomplete sendouts and it goes to 100% with 4 expected recipients left and. So after running that command again it still is stuck at 100% with 4 'Expected recipients'.

![Screenshot 2024-11-28 at 16 46 23](https://github.com/user-attachments/assets/b1ec9ea2-ae14-42a1-920d-e605ef823d4b)

Is there anything else I could look into? For the record, we first used campaign in Craft 4 and this is the first newsletter we send out using Craft 5. Previous sendouts never had this issue going on.

**Comment by bencroker** [comment]
Can you pleased double check that you’re on version 3.5.6 of the plugin? A similar sounding issue was fixed in [3.5.3](https://github.com/putyourlightson/craft-campaign/releases/tag/3.5.3), which is why I ask.

**Comment by dMediaJam** [comment]
I'm having this issue as well. I'm not sure what to make of it. 

I'm using 

PHP 8.3.12
Craft Pro 5.5.5
Campaign: 3.5.7
All plugins are up-to-date.

Here is what I see. 

We send out a daily encouraging email and this is what my current screen shows. See images.

<img width="1247" alt="Screenshot 2024-12-06 at 12 07 16" src="https://github.com/user-attachments/assets/25807424-8dea-4cdf-bb52-82de6f370d0d">
<img width="428" alt="Screenshot 2024-12-06 at 12 06 51" src="https://github.com/user-attachments/assets/3d52b3e5-c438-42cc-84b3-d8fb98159aeb">


Thanks,
Dwayne

**Comment by dMediaJam** [comment]
I'll add more context to mine:

- Each Scheduled Sentout is scheduled to go around 12:30am. It appears that the first couple sent completely. But the last few days, the sendouts are showing as 'pending'.

That last screenshot shows the one that was sent out this morning and it is showing as 'pending'.

Perhaps worth noting is that I did try and send one scheduled sendout too early and I paused it and since deleted it. Did that cause any disruption perhaps?

Thanks,
Dwayne

**Comment by bencroker** [comment]
Can you please try running pending sendouts to see if that clears them out? There are no negative consequences to doing this.
https://putyourlightson.com/plugins/campaign#running-pending-sendouts

**Comment by dMediaJam** [comment]
I ran the following command just now:

`php craft campaign/sendouts/run`

I then saw this in my cli: 

`4 pending  sendout(s) queued.`

I waited for 10 mins.
Nothing happened that I could see. 

This is a screenshot of my export report (i've removed unnecessary columns for this debugging purpose.).

<img width="1337" alt="Screenshot 2024-12-06 at 14 06 30" src="https://github.com/user-attachments/assets/dcdf5b1c-8140-4c20-9489-f90732f8e8f6">

**Comment by bencroker** [comment]
My guess is that those incomplete sendouts each report that there is still at least one expected recipient. Can you please let me know if that is the case (you’ll see the number in the sidebar of the edit sendout pages)? If so then I’ll troubleshoot the query that makes that calculation.

**Comment by dMediaJam** [comment]
I"ll review that and get back to you. 

If it is relevant, here is more info:

-  I am scheduling days ahead but in the meantime I am adding/removing and editing people from the mailing list being used, between the time I schedule the sendout and when it actually gets sent. So does the system take into consideration any users who were added to the mailing list between scheduling the sendout and actually sending? 

I will test the following tomorro:

- For tomorrows email sendout test: I'm going to delay scheduling the sendout until there is a moment when I know that no changes will happen.

I'll let you know what I learn and I'll look into your question.

Dwayne

**Comment by dMediaJam** [comment]
After looking into it,  yes there was one intended recipient who is marked as 'bounced', which matched with my last report which says 1128 successful sendouts and 1 bounce. The status of the campaign appears to sit at 'pending', perhaps until that 'bounced' recipient is resolved somehow?

**Comment by bencroker** [comment]
Yes, that’s most likely the issue. I’ll troubleshoot and let you know as soon as I have a fix.

**Comment by bencroker** [comment]
I’m not 100% sure that this fixes it, but I’ve made it so that the logic for calculating the pending recipient count for scheduled sendouts is now the same as for regular sendouts (which do not appear to have this issue). 

Can you please test using version [3.5.8](https://github.com/putyourlightson/craft-campaign/releases/tag/3.5.8)?

**Comment by lennonpuype** [comment]
> Can you pleased double check that you’re on version 3.5.6 of the plugin? A similar sounding issue was fixed in [3.5.3](https://github.com/putyourlightson/craft-campaign/releases/tag/3.5.3), which is why I ask.

Hi, missed your question, my bad!
My version actually was 3.5.6

I now updated to 3.5.8 and the expected recipients now are 0 so that works as expected now, but the status is still pending with the progress at 100%. Cleared all CP caches but that doesn't change anything.

![Screenshot 2024-12-10 at 15 20 09](https://github.com/user-attachments/assets/ad582760-28a8-4e5f-850f-db565de4481e)

When running the `./craft campaign/sendouts/run` command the sendout is getting queued but it doesn't even start

![Screenshot 2024-12-10 at 15 26 33](https://github.com/user-attachments/assets/ed9ce875-6ef0-4c3f-8cbd-406589cc0ab7)

**Comment by bencroker** [comment]
> I now updated to 3.5.8 and the expected recipients now are 0 so that works as expected now, but the status is still pending with the progress at 100%.

Great, that means that this should fix the issue. If the queue job is stuck, please cancel it and resume sending of the sendout via the sendout edit page.

**Comment by dMediaJam** [comment]
So I believe that the issue has been resolved. Thank you.

**Comment by bencroker** [comment]
Glad to hear it!

**Comment by BrandKits** [comment]
Hi Ben, we've been having the same issue, but on Campaign 2.17.8 / Craft CMS 4.13.3. 

The client team have been noticing for the last 4 weeks that sendouts with 100% progress stay on Pending vs Sent, but I couldn't figure out why. There are a few bounces in each sendout.

We've also just started a series of modals requesting subscriptions, and since then have had many complaints of people getting 10 different campaigns at the same time. 

I suspect it's because they are subscribing to lists where sendouts were still 'pending'– and we have a cron job to do craft campaign/sendouts/run every 10minutes, so new subscribers have been getting multiple old campaigns.

I've just changedt he status of old sendouts with Pending or Queued to Cancelled, but it would be great to get this fix for Craft 4 Campaign.

Thanks

**Comment by bencroker** [comment]
Apologies for the delay in backporting this fix to Campaign 2. I just release [2.17.9](https://github.com/putyourlightson/craft-campaign/releases/tag/2.17.9) with the fix applied.

**Comment by BrandKits** [comment]
Thanks Ben, appreciate the quick response.
