### ISSUE TITLE
Resume sendout automatically

### ISSUE THREAD

**Issue by krizzzly** [putyourlightson/craft-campaign#82]
Hello,

whenever the sending of an email fails, the whole sendout is failed. I wonder why there is no automated retry ?

I can read in CP in sendout detail page: 
Sending failed. Please check your email settings and the error in the log.

The campaign.log has: 
```
2019-07-23 17:35:04 [][][info] Sending of the sendout "test" failed due to invalid Campaign email settings. Check the full error in the Craft log.
```
and the queue.log has:
```
2019-07-23 17:35:04 [-][-][-][warning][application] Error sending email: Expected response code 220 but got an empty respons
```
The email settings are not wrong. Its just the mailserver that probably didnt respond correctly once.

Best regards

**Comment by putyourlightson** [comment]
The reason the entire sendout fails is that the failure indicates an issue with the email settings. This sometimes happens because an SMTP host has throttling in place or a limit on the number of emails it will send within a given timeframe. But I agree with your comment that this could just be a single empty response and that an automated retry would make sense so I'll look into adding it in the next release. Thanks for reporting this!

**Comment by putyourlightson** [comment]
Added the `maxSendAttempts`config setting which defines the maximum number of times to attempt sending a sendout before failing and defaults to `3` in version 1.10.0.
