### ISSUE TITLE
Multiple emails to individual contacts with sendout to multiple mailing lists?

### ISSUE THREAD

**Issue by cquinders** [putyourlightson/craft-campaign#87]
Hi!

I am wondering if a sendout that gets send to multiple mailing lists will be send multiple times to individual contacts that are subscribed to multiple of these mailing lists?

The number of recipients for such a sendout seems to be the sum of all the mailing lists (which in my testing was higher than my total contacts).

I searched the docs, but couldn’t find any information on this.

**Comment by putyourlightson** [comment]
The sending process will ensure that only a single email is sent to each contact, even if some of those contacts are subscribed to multiple mailing lists selected in the sendout. This applies to all sendout types except for recurring sendouts that allow sending to contacts multiple times in the sendout’s settings.

We've added a note ot the docs to clarify:
https://putyourlightson.com/plugins/campaign#how-sendouts-are-sent

The number of recipients you are seeing is a bug, fixed in https://github.com/putyourlightson/craft-campaign/commit/ba0dab6b3f4e33df73be5770a3c2a4aba986b894
