### ISSUE TITLE
FR: Can I have a segment condition for craft user last login 

### ISSUE THREAD

**Issue by john-henry** [putyourlightson/craft-campaign#88]
Hi Ben,

I have a client who got confused by Last Activity not understanding that it was last activity on the newsletter and not last activity on the actual website.

They want to create drip like campaigns that can segment contacts (all Craft Users) based on last login. So for example a segment for all users that have not logged in in the last month.

Would something like that be possible or do you see any issues with it?

I understand that other users of your plugin may not necessarily have User accounts associated with subscribers so that may be a challenge

**Comment by putyourlightson** [comment]
Hi John,

Since contacts are not the same as users, segmenting based on a user's last login is not as trivial as segmenting by one of the properties of a contact. In theory, you should be able to use a template segment to achieve this, although it may not be very performant. 

Here is some untested code to help get you started.

```
{% if contact.userId %}
    {% set user = craft.users
        .id(contact.userId)
        .lastLoginDate('< ' ~ date('30 days ago')|atom)
        .one() 
    %}
    {{ user ? 1 : 0 }}
{% endif %}
```

[Last login date docs](https://docs.craftcms.com/v3/dev/element-queries/user-queries.html#lastlogindate)

**Comment by john-henry** [comment]
@putyourlightson Cheers Ben. I'll give that a go. That should do for now.
